### ISSUE TITLE
App suggestion

### ISSUE THREAD

**Issue by antaeusdk** [TheEvilSkeleton/free-and-open-source-android-apps#8]
Infinity for Reddit: https://github.com/Docile-Alligator/Infinity-For-Reddit (Available on another F-Droid repo: https://apt.izzysoft.de/fdroid/index/apk/ml.docilealligator.infinityforreddit)

**Comment by resynth1943** [comment]
That actually looks pretty good. Thanks for the suggestion! :heart:

**Comment by resynth1943** [comment]
Thanks for contributing. We've added your suggestion in 50e0703c737e7f35439d41107d01808ad1fa8244. :heart:
